(deftheme visk "Railscasts based theme")
 
(custom-theme-set-faces
 'visk
 '(default ((t (:background "#000000"))))
 '(border-color ((t :foreground "#000000")))
 '(cursor-color ((t :foreground "#729ecb")))
 '(foreground-color ((t :foreground "#ffffff")))
 '(mouse-color ((t :foreground "black")))
 '(fringe ((t (:background "#000000"))))
 '(mode-line ((t (:foreground "#eeeeec" :background "#262626"))))
 '(region ((t (:background "#083512"))))
 '(font-lock-builtin-face ((t (:foreground "#729dcb"))))
 '(font-lock-comment-face ((t (:foreground "#aaaaaa"))))
 '(font-lock-function-name-face ((t (:foreground "#ffd100"))))
 '(font-lock-keyword-face ((t (:foreground "#e3871c"))))
 '(font-lock-string-face ((t (:foreground "#70b607"))))
 '(font-lock-type-face ((t (:foreground"#da4939"))))
 '(font-lock-constant-face ((t (:foreground "#eeeeec"))))
 '(font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
 '(minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
 '(font-lock-warning-face ((t (:foreground "red" :bold t))))
 '(font-lock-comment-face ((t (:foreground "#888888"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#888888")))))
 
(provide-theme 'visk)
